# Generated by Django 6.0.1 on 2026-06-04 12:43

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Both', 'Both')], default='First', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capacity', models.IntegerField()),
                ('exam_capacity_single', models.IntegerField(blank=True, help_text='Capacity when hosting 1 course', null=True)),
                ('exam_capacity_mixed', models.IntegerField(blank=True, help_text='Capacity when hosting mixed courses', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEntry',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(db_index=True, max_length=20)),
                ('hall_name', models.CharField(max_length=150)),
                ('slot_label', models.CharField(choices=[('morning', 'Morning (08:15–10:15)'), ('midday', 'Midday (11:00–13:00)'), ('afternoon', 'Afternoon (14:00–17:00)')], max_length=20)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_no', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='CoursePreference',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(db_index=True, max_length=20)),
                ('hall_name', models.CharField(max_length=150)),
                ('venue_weight', models.FloatField(default=0.0)),
                ('morning_weight', models.FloatField(default=0.0)),
                ('midday_weight', models.FloatField(default=0.0)),
                ('afternoon_weight', models.FloatField(default=0.0)),
            ],
            options={
                'unique_together': {('course_code', 'hall_name')},
            },
        ),
        migrations.CreateModel(
            name='TimetableProject',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_session', models.CharField(help_text='e.g 2023/2024', max_length=50)),
                ('semester', models.CharField(help_text='e.g First Semester', max_length=20)),
                ('exam_start_date', models.DateField(blank=True, help_text='First day of exams', null=True)),
                ('exam_end_date', models.DateField(blank=True, help_text='Last day of exams', null=True)),
                ('is_sample_mode', models.BooleanField(default=False, help_text='When True, only the 32-course sample dataset is active for this project.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='scheduling.timetableproject')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectHall',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable this venue for this semester')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.hall')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_halls', to='scheduling.timetableproject')),
            ],
            options={
                'unique_together': {('project', 'hall')},
            },
        ),
        migrations.CreateModel(
            name='ProjectCourse',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_capacity', models.IntegerField(default=0, help_text='Number of students enrolled')),
                ('duration_minutes', models.IntegerField(default=120)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.course')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_courses', to='scheduling.timetableproject')),
            ],
            options={
                'unique_together': {('project', 'course')},
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_allocation', models.IntegerField(default=0)),
                ('preference_guided', models.BooleanField(default=False, help_text='Set when data-driven historical preferences guided this placement')),
                ('constraint_violations', models.JSONField(blank=True, default=list, help_text='List of constraints that were violated for this placement')),
                ('constraints_total', models.IntegerField(default=0, help_text='Total enabled constraints checked')),
                ('constraints_met', models.IntegerField(default=0, help_text='Number of constraints that were satisfied')),
                ('project_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.projectcourse')),
                ('project_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.projecthall')),
                ('timeslot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.timeslot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduling.timetableproject')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_carryover', models.BooleanField(default=False)),
                ('project_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.projectcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.student')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='scheduling.timetableproject')),
            ],
            options={
                'unique_together': {('student', 'project_course')},
            },
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_type', models.CharField(choices=[('student_conflict', 'No student has two exams at the same time'), ('department_conflict', 'No department has two exams at the same time'), ('venue_capacity', 'Venue capacity must accommodate all students')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='scheduling.timetableproject')),
            ],
            options={
                'unique_together': {('project', 'constraint_type')},
            },
        ),
    ]
